### ISSUE TITLE
Forbid player names to start with /

### ISSUE THREAD

**Issue by necropotame** [necropotame/teeworlds-infclass#104]

**Comment by Socialdarwinist** [comment]
Methinks that this is the solution: [https://github.com/FallenKN/openfng/commit/903eb0bdc4161f18db3f18fda2a195ead2535f49](url). Check out the other commits on that repository that prevent abusive names.

**Comment by necropotame** [comment]
The link is not working for me. But a simple approach consists of removing the first / from the name

**Comment by Socialdarwinist** [comment]
Ah well, now it is working, but the URL in the text worked …
