### ISSUE TITLE
Remove username as parameter in ban command

### ISSUE THREAD

**Issue by necropotame** [necropotame/teeworlds-infclass#107]
And remove it as chat command

**Comment by Socialdarwinist** [comment]
Another solution to the username ban calamity would be to implement that, firstly, the RCON spell out usernames as Unicode codepoints on request and, secondly, it be possible to ban abusive usernames using code points and also using regular expressions (maybe restrained by limitations for banning to broad). But of course, the moderators would be too shlubby to use it, only I would look up code points to ban names.

**Comment by Henningstone** [comment]
@Socialdarwinist somebody who thinks that much about banning seems to make up for a pretty good moderator :D
But jokes aside, why make it easy when you can make it complicated, huh? What happened to good old ban-by-CID? If you would even look up Unicode codepoints and use regex to ban people, why wouldn't you just switch on debug mode in your client and look up their IDs? (or ask the server for the IDs...)

Just curious.

**Comment by Socialdarwinist** [comment]
@Henningstone I have never banned anyone by name, always have done it by CID. But against some people, name bans would have more effect, and also, implementation of regex could prevent people from using obscene names. But as I think so far, this would require that the server denies name change requests in game, which is an issue outside of the scope of the ban command.

**Comment by Henningstone** [comment]
> But against some people, name bans would have more effect

Banning somebody by something that can be changed entirely within seconds is not very effective imo. Of course, regex would be more than useful to generally forbid certain offensive names, but that's another topic which has nothing to do with this thread :D

**Comment by Stitch626** [comment]
Nvm, if you ban people by name the ban is just the ip anyway. I think its useless, so lets remove it.

**Comment by necropotame** [comment]
> Nvm, if you ban people by name the ban is just the ip anyway. I think its useless, so lets remove it.

It's already the case and this issue is closed :)
