### ISSUE TITLE
Class and mercenary menu flicker

### ISSUE THREAD

**Issue by Socialdarwinist** [necropotame/teeworlds-infclass#115]

**Comment by necropotame** [comment]
I've experienced this only when the round time is locked because the game wait for players. Do you confirm ?

**Comment by Socialdarwinist** [comment]
I do confirm this; this must be why I only have noticed it today as @Stitch626 has told me about it.  The bad news is that I have just experienced it on newdust when trying to test it – therefore I widen the issue title.

**Comment by duralakun** [comment]
its now also in infc_damascus, its spreading

**Comment by necropotame** [comment]
It's not related to maps, it's related to the number of players. If you are alone, the menu is broken.
