### ISSUE TITLE
Re-connects for beeing an undead

### ISSUE THREAD

**Issue by Defeater** [necropotame/teeworlds-infclass#12]
Today I saw a player who was three times in succession the "undead". When he was infected, he re-connect to the server until he was an undead zombie. 
Maybe we can fix this by adding an 1min-ban for "leaving as infected".

**Comment by argon-radio** [comment]
better not a bann, today there was somebody (he re-connected as well and spammend), who copied ip adresses of presend players, so that we bann ourselfes, maybe just a kick or moving to spectators

**Comment by TheRealOrangus** [comment]
No, it's not good at all, better make so zombies that entered during the round can't become undead or witch.
