### ISSUE TITLE
Biologist laserbomb gets erased on reset attempts averted by proximity requirement

### ISSUE THREAD

**Issue by duralakun** [necropotame/teeworlds-infclass#146]
When you are to far away from a wall to plant your laser bomb, your active laser bomb will disappear, even tough you dident plant a new one. Instead a message should appear "You are to far away to plant the bomb, get closer" and your active laser bomb should only disappear if you successfully planted a new one.

**Comment by Socialdarwinist** [comment]
The mentioned bug does not appear anymore, I do not know why.
