### ISSUE TITLE
Zombie life leech

### ISSUE THREAD

**Issue by duralakun** [necropotame/teeworlds-infclass#162]
Whenever a zombie deals hook damage, it gains the same amount of health back

**Comment by necropotame** [comment]
I don't think it's needed in term of gameplay. There is already a lot of way for infected to be healed, and far more easy to do

**Comment by necropotame** [comment]
I don't think it's needed in term of gameplay. There is already a lot of way for infected to be healed, and far more easy to do

**Comment by duralakun** [comment]
Maybe its too much heal yes
