### ISSUE TITLE
The King Class

### ISSUE THREAD

**Issue by TheRealOrangus** [necropotame/teeworlds-infclass#17]
There may be only 1 human with this class, and only if there's enough players in-game(spectators aren't counted).
Human that will have this class selected randomly.

#### The King
The King may have all weapons, and slow ammo regeneration(1 ammo per 3-5 seconds probably).
The King can place _The Ammo Dispenser_ by hammer.
The King cannot be infected by damage, and get to be infected only when he dies.
When The King dies, a new King selected randomly from humans, chance that some human gonna be the new King is depending to amount of kill in current round(**not** amount of kills in total).

### The Ammo Dispenser
The Ammo Dispenser is a random weapon pickup which contains 1 ammo(picking it up gives 1 more ammo).
When The Ammo Dispenser have been picked up, it gones(just gets invisible and unusable, but still appears there) for 10 seconds, then it appears on the same place, with new random weapon with 1 ammo.
If humans won't pick up ammo from The Ammo Dispenser, it will **not** stack there over time, but will always hold only 1 ammo, so the most efficient way to use it, is to pick ammo from it, right after it appeared.
The Ammo Dispenser does **not** disappears over time.
If zombie touches The Ammo Dispenser, then it explodes and kills everything in it's range.

**Comment by necropotame** [comment]
In the next release, all weapons have ammo regeneration. The ammo dispenser will be useless in this context.

**Comment by TheRealOrangus** [comment]
I still would like to see The King in-game, a class that is much more powerful than others.
Maybe make some super-weapon for him?
~~Like a poweful and fat death ray that goes through tees and kills every zombie by a single hit.~~

**Comment by argon-radio** [comment]
the protector would rather be an engineer item, but then there must be a special rule for placing that turret, it would be too easy to survive if just every engineer places the turrets.


but the protector is a good idea at all.

**Comment by TheRealOrangus** [comment]
> but the protector is a good idea at all.

Everyone likes own turret x)
