### ISSUE TITLE
Slug slime should be prevented from harming when the emitting slug is ninja-frozen

### ISSUE THREAD

**Issue by Socialdarwinist** [necropotame/teeworlds-infclass#177]
This could be a balanced loophole in fighting against slugs, and it is also necessary for sole ninjas fighting slugs.
I am not decided about the question if the slug slime shall reappear after an unfreeze, but I guess it is more consequential if it does not.

**Comment by necropotame** [comment]
I don't get it. Can you describe the situation that is problematic?

**Comment by Socialdarwinist** [comment]
When I freeze a slug as a ninja, I cannot kill the slug with my sword without harming myself, in so far as the slug has slime near it. In the long run the ninja always loses, regardless of his skill, because he may not get near a slug, but has to get near a slug to kill it, because the sword is his almost only weapon. I opine that it would not make the slug too weak if its slime ceased by a freeze.

**Comment by Socialdarwinist** [comment]
Solved by 678a4ed0ebb30c9dd3d8e135a6cc7a879b614ae7.
