### ISSUE TITLE
Witch spawn bug, related to maps

### ISSUE THREAD

**Issue by TheRealOrangus** [necropotame/teeworlds-infclass#18]
I have spawned near a witch, right here:

![image](https://cloud.githubusercontent.com/assets/5873735/10802779/5e50c46a-7dc7-11e5-8abb-5301e57e313d.png)

This is inf_minecraft/inf_warehorse map bug.

**Comment by necropotame** [comment]
I know this problem, and I've fixed it for warehorse_ac before. I will do it for other maps. It's not possible to fix it otherwise since I don't want to search a path from spawner to tile to be sure that an air tile is a part of the playable area.

**Comment by TheRealOrangus** [comment]
I know, that's why I added _`... related to maps`_.

**Comment by necropotame** [comment]
It was not against you. But I prefer to explain clearly possible approach, since it's not obvious to everyone :-)
