### ISSUE TITLE
Don’t kick (so fast) afk players that are alone on the server

### ISSUE THREAD

**Issue by Socialdarwinist** [necropotame/teeworlds-infclass#185]
This would help in acquisition of players, as a lonely player, instead of walking through a map alone for minutes and becoming bored too fast, likely wants to switch to another application in order to attend other occupations, while waiting to be wakened by the server message that somebody has joined.

**Comment by duralakun** [comment]
i like it, so no afk kick when there is only 1 player on?

**Comment by Socialdarwinist** [comment]
At least not as fast as afk kick usually is. The reason of course why one not just joins spectators is that some people instantly leave if they see that the guy on the server is spectator, or even do not join at all because they see it in the server list, and also #186.
What I have not mentioned: It would facilitate testing on a local server. Maybe one can even have a restrained afk kick if all players on a server have the same IP.
