### ISSUE TITLE
Becoming undead having been scientist doesn't reset portals completely

### ISSUE THREAD

**Issue by maxcroud** [necropotame/teeworlds-infclass#209]
1. Two portals are set 
2. The scientist becomes undead 
3. The undead becomes human again (by human hooks) 
4. The scientist makes one portal 
Hereof using this one portal moves player to a spot where previously another portal was set. But actually there are not previous portals neither graphically not physically (player being on spot can't be moved to the real portal).

**Comment by ProgVal** [comment]
Hi,

Portals were removed from InfectionClass about a year ago.

If you are playing on Stitch's servers, don't confuse them with InfectionClass. Stitch forked InfectionClass some time ago and re-added portals.

**Comment by ProgVal** [comment]
Also, in official InfectionClass, undeads cannot be healed. That's also an addition from Stitch.
