### ISSUE TITLE
Bug on inf_skull

### ISSUE THREAD

**Issue by TheRealOrangus** [necropotame/teeworlds-infclass#22]
Bug appears that all spikes are like that shit:
![image](https://cloud.githubusercontent.com/assets/5873735/10815078/64d3bcfa-7e32-11e5-85bb-a5011a7d743e.png)
That bug didn't appear earlier.
Is probably because some tiles(spikes) saved as external, but should be embedded.

**Comment by necropotame** [comment]
Why they must be embedded ? I use the default one. Everybody have this bug, or it's specific to you ? Do you use vanilla client ?

**Comment by TheRealOrangus** [comment]
* I don't use vanilla client usually, but when I switch, it not changes.
* This bug appears not just me, but for some people too.

**Comment by Defeater** [comment]
This is a local problem... You have the "jungle_deathtiles"-mapres in your data/mapres folder?

**Comment by TheRealOrangus** [comment]
Should I?
* I have downloaded client from teeworlds.com, and the bug is still there as I expected.
* That bug was not there earlier, but I didn't change anything in my local, rather you edited the map.

**Comment by Defeater** [comment]
Eh, yes.

- So, only the .exe client? Try to download the full .zip file and start the client from the extracted folder.
- Whats with other maps that include the "jungle_deathtiles"-mapres? Same problem?

**Comment by TheRealOrangus** [comment]
> So, only the .exe client? Try to download the full .zip file and start the client from the extracted folder.

What? That IS exactly how I did, and there are no other ways.

> Whats with other maps that include the "jungle_deathtiles"-mapres? Same problem?

On some maps on some servers this happens too, but not often, _usual_ solution for me was embedding the tiles into the map.

**Comment by Defeater** [comment]
- Well, you could copy&paste the standard-client .exe into your usual teeworlds-folder (where the "jungle_deathtiles"-mapres is missing).
- Thats no solution. The default mapres shouldn't be embedded.

Its a local problem with your computer. Looks like you want no help apparently, so this issue should be closed.

**Comment by necropotame** [comment]
Usually, I use the Linux steam version. Can you give me the link you used to download the vanilla version (to be sure that we talk about the same thing). I want to test with it. If this problems can't be solved easily, I will embedded the image. It the wrong way to do it, but if multiple players have this issue, it's an real issue in term of gameplay.

**Comment by TheRealOrangus** [comment]
> Can you give me the link you used to download the vanilla version

http://downloads.teeworlds.com/teeworlds-0.6.3-win32.zip

**Comment by TheRealOrangus** [comment]
Anyways.. The map seems to haven't this bug now.

**Comment by necropotame** [comment]
I've embedded it, but I still don't know where the bug comes from

**Comment by TheRealOrangus** [comment]
From teeworlds developers...

**Comment by Defeater** [comment]
lol Orangus
