### ISSUE TITLE
Everyone has privileges to change /class on inf_newdust map

### ISSUE THREAD

**Issue by n3tman** [necropotame/teeworlds-infclass#26]
Someone found this bug and it was heavily abused.
You can write /class ninja and become a Ninja even as a Zombie. Worked with all other classes too.
Does not affect inf_mario and inf_warehorse. Not checked on inf_warehorse_ac, inf_skull and inf_minecraft.

**Comment by Defeater** [comment]
Oh yes, this 50 minutes were very funny.
IMO an admin has forgotten to disable "debug mode", and after the map change, it has turned off automatically ;)
