### ISSUE TITLE
Option to automatic disable debug-mode if all admins leave the server

### ISSUE THREAD

**Issue by Defeater** [necropotame/teeworlds-infclass#27]
This would avoid situations like #26.

**Comment by TheRealOrangus** [comment]
Disagree, you should not use debug on the remotely hosted server at all until crash appears, only on your local machine where you test, you can use K-Client for up to 4 tees(3 dummies).

**Comment by necropotame** [comment]
The debugmode rcon command is no longer available. Instead, I've added an rcon command to change the class of any player.
