### ISSUE TITLE
Increase max players to 64

### ISSUE THREAD

**Issue by n3tman** [necropotame/teeworlds-infclass#29]
The server is full in the evenings, I think it's a good idea to increase maximum number of players, if possible. The maps are big, it should be okay with more than 16 players.

**Comment by necropotame** [comment]
I prefer to add a second server, but I don't have a longterm solution for that. You can ask on the forum, maybe someone can help for that.

**Comment by n3tman** [comment]
Cool, thanks. A second sever is good.
