### ISSUE TITLE
Super version of boomer, hunter and zombie

### ISSUE THREAD

**Issue by TheRealOrangus** [necropotame/teeworlds-infclass#31]
This class would be similar to Boomer, but with the following differences:

* MegaBoomer explodes in 3 seconds after hitting fire button.
* MegaBoomer cannot hook after hitting fire button.
* Explosion of MegaBoomer is much bigger than usual, it is actually something like size of soldiers' bombs' explosions.

Unlike to other superclasses of zombies, after death, the zombie still would be MegaBoomer.

**Comment by necropotame** [comment]
* MegaBoomer explodes after 3 seconds. During this time, he is freezes
* MegaBoomer explosion is like the one of the flash grenade, but with explosion instead of hammer hits.
* Any boomer can become megaboomer with a very low chance. But he will respawn as normal boomer after he die
* MegaBoomer explode as normal boomer if he is killed by someone

**Comment by TheRealOrangus** [comment]
> * Any boomer can become megaboomer with a very low chance. But he will respawn as normal boomer after he die

Like what? Like a boomer can become a megaboomer when he spawns, or when he gets infected?
May there be more than 1 megaboomers, same time?

**Comment by necropotame** [comment]
Only one at the same time. Each second, the game generate a random number. If this number is less than <chance to be megaboomer>, then the next boomer that spwan will be a megaboomer. This behaviour will be the same for mega hunter and mega zombie.

**Comment by necropotame** [comment]
Super hunter : can jump infinitely
Super zombie : deal more damage by hooking players and has more strength to catch others

**Comment by TheRealOrangus** [comment]
Would be there just 1 advanced zombie(Super Zombie/Super Hunter/Super Boomer) same time, or just 1 super zombie per super class?

**Comment by argon-radio** [comment]
but then the humans need some better weapons too, like this the zombies get more and more OP.
i would not make the megaboomer freeze after hitting fire button. the mega zombie should not be able to hook farther, only deal more damage and have stronger hook, only on humans. Too i tink, that there only should be low chances for becoming super versions.

what about a minigun for the soldiers? (for example 2 shots per second, with counter, that increases the heat number from 0 to 8 every second fired, and decreases every second not fired, lowest value 0, after reaching 8, the gun cannot fire for 15 seconds, to make it fair for the zombies)

**Comment by TheRealOrangus** [comment]
Well.. Currently now often happens that army of zombies can't catch a single survivour.
Or that some humans finding a good camp points and strategies disallowing zombies to get in completely so there is no chance for them at all.
