### ISSUE TITLE
Add multiple infections area in maps

### ISSUE THREAD

**Issue by necropotame** [necropotame/teeworlds-infclass#34]
All maps should have multiple infection area. Each round, a random area is selected and infected spawn only here. This could makes the game less linear and repetitive.
After 10 seconds, a message explain the location of the infection zone like "infection started in the underground/tower/..."

**Comment by argon-radio** [comment]
so for example there are on infc_damascus four possible zones (for humans to know where not to be in first ten seconds) and one gets randomly selected each round?

or what about a selection system like this: the zone is selected by the amount of players in a region, if there are no players in the tower, the tower gets selected, if there are more people in the tower than in the underground, the underground gets selected.

**Comment by TheRealOrangus** [comment]
If it would be made this way @argon-radio, then players can always go same place, and the infected zone would always be the same, instead of making the zone will less humans to be infected, I suggest to make the zone with highest or middlest amount of humans.

**Comment by argon-radio** [comment]
id rather take the one with the lowest amount of humans, because if the one with the most gets selected, there are suddenly a lot of zombies. with instantly 8 zombies vs 8 survivors the 5-7 minutes (depends on map) would be way to long for the humans to survive.

**Comment by ProgVal** [comment]
If you define 6 spawn area on a map, there will be at least one with 0, 1, or 2 players in it (assuming the number of players is strictly lower than 6*3=18, which is always true in Teeworlds).
So you can make this zone the infection area, and players in it will be initial zombies.
