### ISSUE TITLE
Directional portals

### ISSUE THREAD

**Issue by necropotame** [necropotame/teeworlds-infclass#37]
New appearance : Portal are displayed as ellipse
New behaviour : When the scientist press the fire button with hammer, the portal is oriented in the direction of the cursor. Then, the portal is able to perform rotation of the velocity of the player based on the relative angle between first and second portal.
New collision system : The active zone of the portal is a line, instead of the disk. 
New mechanism : Players can change the direction of bullet when they shoots in a portal. They can also use this to perform super jump.

**Comment by TheRealOrangus** [comment]
Awesome.

**Comment by necropotame** [comment]
Scientists are disabled for now and replaced by medic
