### ISSUE TITLE
Witch abuse

### ISSUE THREAD

**Issue by Defeater** [necropotame/teeworlds-infclass#4]
Zombie-Boomer can do selfkills without respawn-time (and other zombies have only a small respawn time).
So we need a globally spawnprotection, maybe for the first 5secs after spawn, to avoid many selfkills for a witch-spawn.

**Comment by necropotame** [comment]
You mean that peoples do selfkill for fun when there is a witch, or that this make the game too difficult for human ? But yes, waiting 3 seconds if you die in your first 5 seconds seems fair.

**Comment by Defeater** [comment]
There is no 50% chance of spawning near a witch - with selfkills, its up to 100%. That was probably not the intention behind the witch.

**Comment by necropotame** [comment]
For boomer : I will add a respawn time of 3 seconds.
For the others, a selfkill implies that you can't spawn near the witch. Is it okay for you ?

**Comment by Defeater** [comment]
Why not just a respawn protection for 3 seconds - for all -, so that they cant selfkill or spawnkill?
A 3 seconds respawn time will only slow down the gameplay..

**Comment by necropotame** [comment]
What do you mean by respawn protection ? What is the difference with respawn time ?

**Comment by Defeater** [comment]
The player can spawn, but cant selfkill or take damage for 3 seconds.

**Comment by TheRealOrangus** [comment]
* Spawn protection is some time limit, _after_ player has spawned, and during this time, is invulnerable.
* @Defeater, it seems for me like you seeing something buggy or abusable because you don't understand the gameplay and gamerules completely.

**Comment by Defeater** [comment]
Thats maybe the reason xD
