### ISSUE TITLE
Medic

### ISSUE THREAD

**Issue by necropotame** [necropotame/teeworlds-infclass#40]
### New health/armor mechanics
All pickups (armor / health) will disapear (or will be non-renewable). But the question of how take damage is possible is asked, since zombie infect instead of dealing damage. Actually, the can allow to deal damage by
* Hooking a human as smoker
* Using soldier bombs on oneself
This is not enough to provide good gameplay with healing. One solution can be to transfer the ability of smoker to all classes, but with less damage.

### Medic class
Possible action for hammer :
* Heal human
* Build heal zone
Possible action for grenade :
* Heal human (throwing a heart, for example)
Possible normal weapon :
* Shotgun, same as scientist
* Shotgun, but like a heavy weapon : lots of unprecise bullets, with recoil (but you can't fly with it)

Possible ability : transform infected to human with a very low chance.

**Comment by TheRealOrangus** [comment]
> Possible ability : transform infected to human with a very low chance.
Don't add this, otherwise would be hardly abused.
