### ISSUE TITLE
New class: The sniffer

### ISSUE THREAD

**Issue by necropotame** [necropotame/teeworlds-infclass#46]
The sniffer is a rare infected that can detect the position of a human. This detection can be implemented in two manner :

Solution A: A laser dot indicate the direction of the target

Solution B: The target emit splash effect that are only visible for the sniffer. The splash effects follow the target and indicate the path to find him.

If the sniffer infect the target, he obtains +5 points. In addition, since the sniffer use his nose to understand the world, he is insensible to flash grenades

**Comment by TheRealOrangus** [comment]
Awesome :D

**Comment by argon-radio** [comment]
solution B is good, nice idea :)

**Comment by necropotame** [comment]
The sniffer should be also insensible to the poisoned grenades of the mercenary.

**Comment by ObaniGemini** [comment]
if the sniffer is insensible to the most important disturbing weapons, I think it should only gain +3 points by infecting.

I think the solution A would be the best :
- easy to implement, because also already implemented
- easily noticeable, even with no sound
