### ISSUE TITLE
New class: The golem

### ISSUE THREAD

**Issue by necropotame** [necropotame/teeworlds-infclass#47]
The golem is a regular infected class that is insensible to weapon push effect.

**Comment by TheRealOrangus** [comment]
Nice.

**Comment by argon-radio** [comment]
will the insensibility of the hunters be removed then?

**Comment by necropotame** [comment]
No, the golem is replaced by the hunter. I close this topic

**Comment by argon-radio** [comment]
so triple jump will be removed in next version?
