### ISSUE TITLE
HUD improvements

### ISSUE THREAD

**Issue by nowlnowl** [necropotame/teeworlds-infclass#53]
Hey necropotame, nowl here.

I't would be nice to have a countdown in the HUD for the engineer, so you know how long time the wall has left, especially when you are far away.

It would help the soldier aswell to see how many bombs deployed.

The ninja and medic is harder. Maybe the medic can see how many shields all the humans are missing (example 30 shields of 80).

I would also want to see medic auto renew shield every minute or 30 seconds.

**Comment by necropotame** [comment]
It's not possible in the current state of tee worlds to do such interface. Sadly....
