### ISSUE TITLE
Zombies can be spawned in wall when witch happen to be near it

### ISSUE THREAD

**Issue by kputsie** [necropotame/teeworlds-infclass#54]
Well, title of issue is self-describing, so here is screenshot
![](https://cloud.githubusercontent.com/assets/13908160/13328003/6d2b9764-dbfd-11e5-90fa-c57a2e4d40c0.png)

**Comment by necropotame** [comment]
There is already something to prevent that, but apparently, it fail sometimes. I check what is wrong. Thanks.
