### ISSUE TITLE
I think it was a bug with the classes....

### ISSUE THREAD

**Issue by Neko-Neko-Yuki** [necropotame/teeworlds-infclass#55]
While I was playing teeworlds infclass sever 2 I came across on one of the rounds that you could play as a scientist, was it a bug or something else?

**Comment by necropotame** [comment]
No, sometimes, I enable it as special event. Sorry for that ^^

**Comment by Neko-Neko-Yuki** [comment]
Oh ok,  would you be able to enable it as a regular class then?

On Thursday, March 3, 2016, necropotame <notifications@github.com> wrote:
> No, sometimes, I enable it as special event. Sorry for that ^^
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci4.googleusercontent.com/proxy/mkcLFCSwni87T-cD0l73aDhFvsw3Rg0jin0TpPBJ0XrANH_42dzi0s3zGLFngBoDQbvn8yrQt_mGj16Ti52JcrdVuIS_3BQMUKUK929rKO8y_4joS41yXOdHQn0O2_XNL7igWA3SoEyRaqCeLCxLpN7AJiTSSQ=s0-d-e1-ft#https://github.com/notifications/beacon/AQyVO9V1mnEE777pi6RY4C4Ls2lsikzDks5pppQ4gaJpZM4Hn1m0.gif
>

**Comment by necropotame** [comment]
No, because scientist break the game most of the time. I need to make a different version of him, but it's for later.

**Comment by Neko-Neko-Yuki** [comment]
ok, i hope you fix this soon ^^
