### ISSUE TITLE
Upload  basic script infected

### ISSUE THREAD

**Issue by jeulis** [necropotame/teeworlds-infclass#59]
Can you upload the basic script to put in the config server classes for infected and normal infected ? thank you . <In binary> ^^

**Comment by jeulis** [comment]
Et je voulais aussi te demander si tu connaissais un Popold et un ~shapii* ? Je voudrait faire des maps pour avoir plus de choix lorsque je met "inf" mais je trouve pas de binaire pour ce mode...

**Comment by jeulis** [comment]
And I also wanted to ask you if you knew a Popold and shapii * ~ ? I would like to make maps for more choice when I put " inf" but I find no binary for this mode ...

**Comment by necropotame** [comment]
I don't understand your first question. A default config file is available in the repository (autoexec.cfg), if it's what you want :)
About mapping, there is no binaries availalble, so you need to compile the mod yourself. But if it's just for mapping, you can simply use the default editor and replace the entities file with this one: https://github.com/necropotame/teeworlds-infclass/blob/master/data/editor/entities.png (the green tile is for the infected area)

**Comment by jeulis** [comment]
thank you for your answer , only I know to use the default software without problems . But infects not a default mode , how did I know what to encode ? To have a server infected me how to have a standard downloadable mod infected? ( Not by classes, I do not want to steal your idea , except if you will that I use )

**Comment by necropotame** [comment]
This mod, "InfectionClass", doesn’t support "Infection" mod, i.e., the "old" mod without classes.
If you want to setup a server with Infection mod, you must find a binary or sources for this mod. Then, the installation of your server should be similar to official Teeworlds.
If you want to create your own flavour of Infection mod, you can start from the official sources of Teeworlds. It's a good exercise to make such "simple" mod (simple in the sense that you only need basic knowledge about Teeworlds and C++ to do it). The official forum of Teeworlds can help you about that.

**Comment by jeulis** [comment]
oh, i see :) So this mean I can find the classic mod infected teeworld in the official site? And what C ++ ?

**Comment by jeulis** [comment]
No, I know what it is that the C language
XD

**Comment by jeulis** [comment]
but where do you find the basic infected mod 's official website ??

**Comment by jeulis** [comment]
et est-ce qu'il est possible que teeworlds supporte le C et non le C++ ?

**Comment by jeulis** [comment]
and is it possible that teeworlds supports C and not C ++ ?

**Comment by necropotame** [comment]
Le code d'Infection a été perdu, mais d'autre l'on refait. Tu trouvera des liens sur le forum officiel de Teeworlds.

Toutes ces questions ne sont pas reliées à InfectionClass, donc je t'invite à aller discuter de tout ça sur le site officiel de Teeworlds, plutôt que sur le GitHub concernant le développement de InfectionClass. Je clos le sujet.
