### ISSUE TITLE
infection class open for all ?

### ISSUE THREAD

**Issue by jeulis** [necropotame/teeworlds-infclass#60]
met-tu à disposition le binaire d'infection classes ? :) désolé de m'être écarté du sujet précédent.

**Comment by necropotame** [comment]
Non, je ne met pas de binaire à disposition, seulement les sources. Ça prendrait trop de temps de compiler sur chaque plateforme à chaque fois que je fait une mise à jour. Mais InfectionClass reste disponible pour tout le monde car les sources sont public.

**Comment by jeulis** [comment]
D'accord, Merci de l'explication. Comment se sert-on donc des sources alors ? Il faut rentrer ces scripts dans le rcon ?

**Comment by jeulis** [comment]
?
