### ISSUE TITLE
Server is gone

### ISSUE THREAD

**Issue by NanoSlime** [necropotame/teeworlds-infclass#68]
So... What happened to the server?

Also side note, Spider needs to be nerfed, Once a spider grabs onto a human it has infinite grab, basically the human cannot escape and cannot move and will die.

**Comment by necropotame** [comment]
My server is currently attacked using DDoS. The servers will be not available until the end of the attack.

The bug with the spider will be fixed. However, it's kind of random and not always, the grab is infinite.
