### ISSUE TITLE
Crashbug in Lasermine (?)

### ISSUE THREAD

**Issue by Stitch626** [necropotame/teeworlds-infclass#69]
Today my test server crashed.

Gamecontext::CreateLaserDotEvent, in call 
State.m_SnapID = Server()->SnapNewID(); .

Code were unable to get new id (too much mines?). Called via growingexplosion.h. Line 179.

"                                   if(NumPossibleStartPoint > 0)
                                    {
                                        int randNb = rand()%NumPossibleStartPoint;
                                        vec2 StartPoint = PossibleStartPoint[randNb];
                        this one    ->            GameServer()->CreateLaserDotEvent(StartPoint, EndPoint, Server()->TickSpeed()/6);
                                    }"

VS said:

dbg_break -> dbg_asser_imp -> CSnapIDPool -> CServer::SnapNewID -> CGameContext::CreateLaserDotEvent -> CGrowingExplosion<6>::Tick -> CGameWorld::Tick -> CGameContext::OnTick -> CServer::Run -> main.

So bug happend in growingexplosion.h called via lasermine (i think).

I will close VS soon, but i hope my bugreport helps...

**Comment by necropotame** [comment]
Apparently, I don't free correctly Ids. I will check that. Thanks

2016-07-28 17:35 GMT+02:00 Stitch626 <notifications@github.com>:

**Comment by necropotame** [comment]
Closed since I've not experienced it.
