### ISSUE TITLE
New map?

### ISSUE THREAD

**Issue by rattbag** [necropotame/teeworlds-infclass#72]
Several months ago, I mentioned a large map and suggested it be added to the rotation. I've recently got back into Teeworlds, and found the map in an [obscure archive online](http://heinrich5991.de/teeworlds/maps/maps/). The map's name in that list is 'inf_minecraft_XL_25May_aa7f9c0a.map', and [here's a direct download link](http://heinrich5991.de/teeworlds/maps/maps/inf_minecraft_XL_25May_aa7f9c0a.map). 

This used to be the favourite map of the server that used to host it, because it is _huge_ for an infection map. There are lots of places to base on this map, and many routes around it.

**Comment by necropotame** [comment]
I've played on this map with the regular Infection mod. IMO, it's not appropriate for InfClass. Just imagine running after a mercenary in this map, I sure it will be boring. In addition, the theme of the map doesn't fit InfClass (infc_warehouse should be deleted or reskined as well).

**Comment by ProgVal** [comment]
What is wrong with infc_warehouse?

**Comment by necropotame** [comment]
The style is not appropriate in comparison to the most recent map: infc_damascus, infc_bamboo and infc_eidalfitr. In particular, I try to avoid modern element, and I add pseudo perspective (infc_damascus should be fixed too).
