### ISSUE TITLE
Vulnerability of Stun Ability of Ninja

### ISSUE THREAD

**Issue by erayerdin** [necropotame/teeworlds-infclass#79]
Now, As I am zombie, I use this in some cases, too.

# Problem
When ninja stuns you, you can kill yourself so that he cannot take points. This is annoying for ninja players for some cases. They stun you, but cannot kill you, since you suicide right before he acts.

# Possible Solution
Suicide ban for this particular ability. Zombies cannot suicide when they are stunned by a ninja.

**Comment by necropotame** [comment]
The Ninja always got a point when a frozen infected dies, even if the infected is killed by someone else or suicide. I'm not sure if a sound notify it, but the point is effectivly added in the score (tested right now)

**Comment by erayerdin** [comment]
Strange. A player was just mumbling about that. If tested, I am closing the issue right away.
