### ISSUE TITLE
Map download doesn't work with TeeWorlds 0.6.4

### ISSUE THREAD

**Issue by ProgVal** [necropotame/teeworlds-infclass#81]
Hi,

I cannot connect to the official servers anymore, my client is stuck at 0% of the map download.

**Comment by necropotame** [comment]
I've updated the server this morning. The client crashes or just don't download anything ? The server was full hours ago, so the error is not for everybody.

**Comment by ProgVal** [comment]
The client does not download anything.

I had the same problem with the test server for a while, by the way.

**Comment by necropotame** [comment]
Are you using TeeWorlds 0.6.4 ? The map download for this version is broken

**Comment by ProgVal** [comment]
Yes

**Comment by ProgVal** [comment]
Yes. Earlier versions have a security vulnerability, so I do not want to use them.

**Comment by ProgVal** [comment]
Could you update the repo with the new maps, so I can download them manually?

**Comment by necropotame** [comment]
No, because the server process them (what you download is different to the original map). Use DDNet or TeeWorlds 0.6.3 to download them.

**Comment by ProgVal** [comment]
Using DDNet or TeeWorlds 0.6.3 is not an option for me, so I bisected the bug.

It is specific to InfClass servers, and appeared on this commit: 17af4a2e3ba4c3d63101ec008e405ec4f90aeba5

**Comment by necropotame** [comment]
It's specific to servers that implement fast download. It's a known bug that 0.6.4 is not compatible with it. I've to check how DDNet solved it. I will gives you a link later with all processed maps

**Comment by ProgVal** [comment]
Thanks!

**Comment by necropotame** [comment]
You can download all processed maps here: http://infclass.r0x.tw/maps/

**Comment by ProgVal** [comment]
Thanks!

Out of curiosity, what kind of processing does the server do?

**Comment by ProgVal** [comment]
Also, could you add maps of the test server?

**Comment by Stitch626** [comment]
My client got the 0.6.4 security update with a little fix for fast map download. So i havent any problems like that :)

**Comment by ProgVal** [comment]
Where is the code of your client?

**Comment by Stitch626** [comment]
Closed source. ^^

**Comment by ProgVal** [comment]
@necropotame The domain r0x.tw expired yesterday, so your link is broken.
I can provide you with a subdomain of aperio.fr if you wish, I just need to know the IP address(es).

**Comment by ProgVal** [comment]
Actually, I managed to access it using /etc/hosts; but new maps (infc_provence, maybe others) are not available to download

**Comment by necropotame** [comment]
The domain is now infclass.r0x.fr
I will remove add the new maps

**Comment by ProgVal** [comment]
thanks!

**Comment by ProgVal** [comment]
Any news?

**Comment by necropotame** [comment]
Solution here: https://github.com/ddnet/ddnet/pull/591

**Comment by ProgVal** [comment]
\o/

**Comment by Stitch626** [comment]
Code here: https://github.com/Stitch626/teeworlds-infclass/commit/d4798bc512ee0488d4deedf6c5adc211ca0bcf2a
