### ISSUE TITLE
Kicking banned people

### ISSUE THREAD

**Issue by duralakun** [necropotame/teeworlds-infclass#91]
Right now when a player gets banned (after he leaves as start zombie)
All other players with the same IP get kicked.
But instead it would be better if players with the same IP could continue to play but not join the server.

**Comment by Stitch626** [comment]
Hm, this case should be really rare, but we need a nopdrop ban then.

**Comment by duralakun** [comment]
Yes this case is rare, but i saw it happen.
Imagine playing on a lan party and then one guy makes something stupid,
Why does everyone has to be banned for it?
