### ISSUE TITLE
Banning leaver only if leaving causes infection

### ISSUE THREAD

**Issue by duralakun** [necropotame/teeworlds-infclass#93]
When you get infected at the start of a round and then leave, someone else gets infected.
So the leaving player gets banned, so he cant abuse this.

But sometimes it happens that a zombie leaves and gets banned,
even though no one else got infected because he left.

**Comment by ProgVal** [comment]
This used to happen when there were four players. However, I believe this seems to be fixed in 1c45d7f1.
Can you confirm you still have that issue?

**Comment by necropotame** [comment]
I'm sure that may check are not good. I was lazy and I've not created an unified function to check if someone need to be infected in the current state of the game.

**Comment by Stitch626** [comment]
I personally did in my mod. Cause i've seen this coming up :D

**Comment by ProgVal** [comment]
@Stitch626 Could you send a PR with your patch?
