### ISSUE TITLE
Aphrodisiac bombs don't work on boomers

### ISSUE THREAD

**Issue by duralakun** [necropotame/teeworlds-infclass#98]
Mercenary's heart bomb makes zombies friendly for a short time.
But not boomers, they can still explode and infect humans.
Boomers should not be able to explode while influenced by the heart bomb.

**Comment by Socialdarwinist** [comment]
Boomers stll infect when using a suicide bind or when killed by a human.

**Comment by ProgVal** [comment]
It's not a bug, it's a feature.

**Comment by ProgVal** [comment]
hmm, suicide bind is not, though.
